//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admAsocAcumConcepto
    {
        public int CIDCONCEPTOTIPOACUMULADO { get; set; }
        public int CIDCONCEPTODOCUMENTO { get; set; }
        public int CIDTIPOACUMULADO { get; set; }
        public int CIMPORTEMODELO { get; set; }
        public int CSUMARESTA { get; set; }
    }
}
