//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admAcumuladosTipos
    {
        public int CIDTIPOACUMULADO { get; set; }
        public string CNOMBRE { get; set; }
        public int CTIPOOWNER1 { get; set; }
        public int CTIPOOWNER2 { get; set; }
        public int CTIPOACTUALIZACION { get; set; }
        public int CTIPOMONEDA { get; set; }
    }
}
