//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admAsientosContable
    {
        public int CIDASIENTOCONTABLE { get; set; }
        public string CNUMEROASIENTOCONTABLE { get; set; }
        public string CNOMBREASIENTOCONTABLE { get; set; }
        public int CFRECUENCIA { get; set; }
        public int CORIGENFECHA { get; set; }
        public int CTIPOPOLIZA { get; set; }
        public int CORIGENNUMERO { get; set; }
        public int CORIGENCONCEPTO { get; set; }
        public string CCONCEPTO { get; set; }
        public string CDIARIO { get; set; }
        public string CTIMESTAMP { get; set; }
    }
}
