//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admAsocCargosAbono
    {
        public int CIDAUTOINCSQL { get; set; }
        public int CIDDOCUMENTOABONO { get; set; }
        public int CIDDOCUMENTOCARGO { get; set; }
        public double CIMPORTEABONO { get; set; }
        public double CIMPORTECARGO { get; set; }
        public System.DateTime CFECHAABONOCARGO { get; set; }
        public int CIDDESCUENTOPRONTOPAGO { get; set; }
        public int CIDUTILIDADPERDIDACAMB { get; set; }
        public int CIDAJUSIVA { get; set; }
    }
}
