//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admBandera
    {
        public int CIDBANDERA { get; set; }
        public string CNOMBREBANDERA { get; set; }
        public string CBANDERA { get; set; }
        public string CCLAVEISO { get; set; }
    }
}
