//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admClasificacionesValore
    {
        public int CIDVALORCLASIFICACION { get; set; }
        public string CVALORCLASIFICACION { get; set; }
        public int CIDCLASIFICACION { get; set; }
        public string CCODIGOVALORCLASIFICACION { get; set; }
        public string CSEGCONT1 { get; set; }
        public string CSEGCONT2 { get; set; }
        public string CSEGCONT3 { get; set; }
    }
}
