//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admCuentasBancaria
    {
        public int CIDCUENTA { get; set; }
        public string CACCOUNTID { get; set; }
        public string CNUMEROCUENTA { get; set; }
        public string CNOMBRECUENTA { get; set; }
        public System.DateTime CFECHAALTA { get; set; }
        public System.DateTime CFECHABAJA { get; set; }
        public int CESTATUS { get; set; }
        public string CCLABE { get; set; }
        public string CCLAVE { get; set; }
        public string CSEGCONT01 { get; set; }
        public string CSEGCONT02 { get; set; }
        public string CSEGCONT03 { get; set; }
        public string CTEXTOEXTRA1 { get; set; }
        public string CTEXTOEXTRA2 { get; set; }
        public string CTEXTOEXTRA3 { get; set; }
        public System.DateTime CFECHAEXTRA { get; set; }
        public double CIMPORTEEXTRA1 { get; set; }
        public double CIMPORTEEXTRA2 { get; set; }
        public double CIMPORTEEXTRA3 { get; set; }
        public double CIMPORTEEXTRA4 { get; set; }
        public string CTIMESTAMP { get; set; }
        public int CIDMONEDA { get; set; }
        public int CIDCATALOGO { get; set; }
        public int CTIPOCATALOGO { get; set; }
        public string CNOMBANEXT { get; set; }
        public string CRFCBANCO { get; set; }
    }
}
