//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admConversionesUnidad
    {
        public int CIDAUTOINCSQL { get; set; }
        public int CIDUNIDAD1 { get; set; }
        public int CIDUNIDAD2 { get; set; }
        public double CFACTORCONVERSION { get; set; }
    }
}
