//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admCostosHistorico
    {
        public int CIDCOSTOH { get; set; }
        public int CIDPRODUCTO { get; set; }
        public int CIDALMACEN { get; set; }
        public System.DateTime CFECHACOSTOH { get; set; }
        public double CCOSTOH { get; set; }
        public double CULTIMOCOSTOH { get; set; }
        public int CIDMOVIMIENTO { get; set; }
        public string CTIMESTAMP { get; set; }
    }
}
