//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admDocumentosModelo
    {
        public int CIDDOCUMENTODE { get; set; }
        public string CDESCRIPCION { get; set; }
        public int CNATURALEZA { get; set; }
        public int CAFECTAEXISTENCIA { get; set; }
        public int CMODULO { get; set; }
        public double CNOFOLIO { get; set; }
        public int CIDCONCEPTODOCTOASUMIDO { get; set; }
        public int CUSACLIENTE { get; set; }
        public int CUSAPROVEEDOR { get; set; }
        public int CIDASIENTOCONTABLE { get; set; }
    }
}
