//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admDomicilio
    {
        public int CIDDIRECCION { get; set; }
        public int CIDCATALOGO { get; set; }
        public int CTIPOCATALOGO { get; set; }
        public int CTIPODIRECCION { get; set; }
        public string CNOMBRECALLE { get; set; }
        public string CNUMEROEXTERIOR { get; set; }
        public string CNUMEROINTERIOR { get; set; }
        public string CCOLONIA { get; set; }
        public string CCODIGOPOSTAL { get; set; }
        public string CTELEFONO1 { get; set; }
        public string CTELEFONO2 { get; set; }
        public string CTELEFONO3 { get; set; }
        public string CTELEFONO4 { get; set; }
        public string CEMAIL { get; set; }
        public string CDIRECCIONWEB { get; set; }
        public string CPAIS { get; set; }
        public string CESTADO { get; set; }
        public string CCIUDAD { get; set; }
        public string CTEXTOEXTRA { get; set; }
        public string CTIMESTAMP { get; set; }
        public string CMUNICIPIO { get; set; }
        public string CSUCURSAL { get; set; }
    }
}
