//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admDatosAddenda
    {
        public int CIDAUTOINCSQL { get; set; }
        public int IDADDENDA { get; set; }
        public int TIPOCAT { get; set; }
        public int IDCAT { get; set; }
        public int NUMCAMPO { get; set; }
        public string VALOR { get; set; }
    }
}
