//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admEjercicio
    {
        public int CIDEJERCICIO { get; set; }
        public int CNUMEROEJERCICIO { get; set; }
        public System.DateTime CFECINIPERIODO1 { get; set; }
        public System.DateTime CFECINIPERIODO2 { get; set; }
        public System.DateTime CFECINIPERIODO3 { get; set; }
        public System.DateTime CFECINIPERIODO4 { get; set; }
        public System.DateTime CFECINIPERIODO5 { get; set; }
        public System.DateTime CFECINIPERIODO6 { get; set; }
        public System.DateTime CFECINIPERIODO7 { get; set; }
        public System.DateTime CFECINIPERIODO8 { get; set; }
        public System.DateTime CFECINIPERIODO9 { get; set; }
        public System.DateTime CFECINIPERIODO10 { get; set; }
        public System.DateTime CFECINIPERIODO11 { get; set; }
        public System.DateTime CFECINIPERIODO12 { get; set; }
        public System.DateTime CFECHAFINAL { get; set; }
        public int CEJERCICIO { get; set; }
    }
}
