//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admMoneda
    {
        public int CIDMONEDA { get; set; }
        public string CNOMBREMONEDA { get; set; }
        public string CSIMBOLOMONEDA { get; set; }
        public int CPOSICIONSIMBOLO { get; set; }
        public string CPLURAL { get; set; }
        public string CSINGULAR { get; set; }
        public string CDESCRIPCIONPROTEGIDA { get; set; }
        public int CIDBANDERA { get; set; }
        public int CDECIMALESMONEDA { get; set; }
        public string CTIMESTAMP { get; set; }
        public string CCLAVESAT { get; set; }
    }
}
