//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admMaximosMinimo
    {
        public int CIDAUTOINCSQL { get; set; }
        public int CIDALMACEN { get; set; }
        public int CIDPRODUCTO { get; set; }
        public int CIDPRODUCTOPADRE { get; set; }
        public double CEXISTENCIAMINBASE { get; set; }
        public double CEXISTENCIAMAXBASE { get; set; }
        public double CEXISTMINNOCONVERTIBLE { get; set; }
        public double CEXISTMAXNOCONVERTIBLE { get; set; }
        public string CZONA { get; set; }
        public string CPASILLO { get; set; }
        public string CANAQUEL { get; set; }
        public string CREPISA { get; set; }
    }
}
