//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admMovimientosCapa
    {
        public int CIDAUTOINCSQL { get; set; }
        public int CIDMOVIMIENTO { get; set; }
        public int CIDCAPA { get; set; }
        public System.DateTime CFECHA { get; set; }
        public double CUNIDADES { get; set; }
        public int CTIPOCAPA { get; set; }
        public int CIDUNIDAD { get; set; }
    }
}
