//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admMovtosInvFisicoSerieCa
    {
        public int CIDSERIECAPA { get; set; }
        public int CIDMOVTOINVENTARIOFISICO { get; set; }
        public int CIDPRODUCTO { get; set; }
        public string CNUMEROSERIE { get; set; }
        public int CIDALMACEN { get; set; }
        public int CTIPO { get; set; }
        public string CNUMEROLOTE { get; set; }
        public System.DateTime CFECHACADUCIDAD { get; set; }
        public System.DateTime CFECHAFABRICACION { get; set; }
        public string CPEDIMENTO { get; set; }
        public string CADUANA { get; set; }
        public System.DateTime CFECHAPEDIMENTO { get; set; }
        public double CTIPOCAMBIO { get; set; }
        public double CCANTIDAD { get; set; }
        public int CIDCAPA { get; set; }
    }
}
