//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admMovtosBancario
    {
        public string CTRANSACTIONID { get; set; }
        public string CACCOUNTID { get; set; }
        public int CIDCUENTA { get; set; }
        public int CIDDOCUMENTO { get; set; }
        public System.DateTime CFECHA { get; set; }
        public string CDESCRIPCION { get; set; }
        public string CREFERENCIA { get; set; }
        public double CIMPORTE { get; set; }
        public int CESTADO { get; set; }
        public string CTEXTOEXTRA1 { get; set; }
        public string CTEXTOEXTRA2 { get; set; }
        public string CTEXTOEXTRA3 { get; set; }
        public System.DateTime CFECHAEXTRA { get; set; }
        public double CIMPORTEEXTRA1 { get; set; }
        public double CIMPORTEEXTRA2 { get; set; }
        public double CIMPORTEEXTRA3 { get; set; }
        public double CIMPORTEEXTRA4 { get; set; }
        public string CTIMESTAMP { get; set; }
    }
}
