//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admMovtosInvFisico
    {
        public int CIDMOVIMIENTO { get; set; }
        public int CIDPRODUCTO { get; set; }
        public int CIDALMACEN { get; set; }
        public int CIDUNIDAD { get; set; }
        public double CUNIDADES { get; set; }
        public double CUNIDADESNC { get; set; }
        public double CUNIDADESCAPTURADAS { get; set; }
        public int CMOVTOOCULTO { get; set; }
        public int CIDMOVTOOWNER { get; set; }
    }
}
