//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admMovimientosPrepoliza
    {
        public int CIDMOVIMIENTOPREPOLIZA { get; set; }
        public int CIDPREPOLIZA { get; set; }
        public int EJE { get; set; }
        public int PERIODO { get; set; }
        public int TIPOPOL { get; set; }
        public int NUMPOL { get; set; }
        public int MOVTO { get; set; }
        public string CUENTA { get; set; }
        public int TIPOMOV { get; set; }
        public string REFERENCIA { get; set; }
        public double IMPORTE { get; set; }
        public string DIARIO { get; set; }
        public double MONEDA { get; set; }
        public string CONCEPTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string SEGNEG { get; set; }
    }
}
