//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admProductosDetalle
    {
        public int CIDPRODUCTO { get; set; }
        public int CTIPOPRODUCTO { get; set; }
        public int CIDPRODUCTOPADRE { get; set; }
        public int CIDVALORCARACTERISTICA1 { get; set; }
        public int CIDVALORCARACTERISTICA2 { get; set; }
        public int CIDVALORCARACTERISTICA3 { get; set; }
        public string CTIMESTAMP { get; set; }
    }
}
