//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admPrepoliza
    {
        public int CIDPREPOLIZA { get; set; }
        public int CESTADOCONTABLE { get; set; }
        public int EJE { get; set; }
        public int PERIODO { get; set; }
        public int TIPOPOL { get; set; }
        public int NUMPOL { get; set; }
        public int CLASE { get; set; }
        public int IMPRESA { get; set; }
        public string CONCEPTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public double CARGOS { get; set; }
        public double ABONOS { get; set; }
        public string DIARIO { get; set; }
        public int SISTORIG { get; set; }
        public string CHORA { get; set; }
        public string CGUIDPOLIZA { get; set; }
    }
}
