//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admPreciosCompra
    {
        public int CIDAUTOINCSQL { get; set; }
        public int CIDPRODUCTO { get; set; }
        public int CIDPROVEEDOR { get; set; }
        public double CPRECIOCOMPRA { get; set; }
        public int CIDMONEDA { get; set; }
        public string CCODIGOPRODUCTOPROVEEDOR { get; set; }
        public int CIDUNIDAD { get; set; }
        public string CTIMESTAMP { get; set; }
    }
}
