//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admProyecto
    {
        public int CIDPROYECTO { get; set; }
        public string CCODIGOPROYECTO { get; set; }
        public string CNOMBREPROYECTO { get; set; }
        public System.DateTime CFECHAALTA { get; set; }
        public System.DateTime CFECHABAJA { get; set; }
        public int CESTATUS { get; set; }
        public int CIDVALORCLASIFICACION1 { get; set; }
        public int CIDVALORCLASIFICACION2 { get; set; }
        public int CIDVALORCLASIFICACION3 { get; set; }
        public int CIDVALORCLASIFICACION4 { get; set; }
        public int CIDVALORCLASIFICACION5 { get; set; }
        public int CIDVALORCLASIFICACION6 { get; set; }
        public double CIMPORTE1 { get; set; }
        public double CIMPORTE2 { get; set; }
        public string CSEGCONT1 { get; set; }
        public string CSEGCONT2 { get; set; }
        public string CSEGCONT3 { get; set; }
        public string CTEXTOEXTRA1 { get; set; }
        public string CTEXTOEXTRA2 { get; set; }
        public string CTEXTOEXTRA3 { get; set; }
        public System.DateTime CFECHAEXTRA { get; set; }
        public double CIMPORTEEXTRA1 { get; set; }
        public double CIMPORTEEXTRA2 { get; set; }
        public double CIMPORTEEXTRA3 { get; set; }
        public double CIMPORTEEXTRA4 { get; set; }
        public string CTIMESTAMP { get; set; }
        public int CTIPOCATALOGO { get; set; }
        public int CIDCATALOGO { get; set; }
    }
}
