//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admPromocione
    {
        public int CIDPROMOCION { get; set; }
        public string CCODIGOPROMOCION { get; set; }
        public string CNOMBREPROMOCION { get; set; }
        public System.DateTime CFECHAINICIO { get; set; }
        public System.DateTime CFECHAFIN { get; set; }
        public double CVOLUMENMINIMO { get; set; }
        public double CVOLUMENMAXIMO { get; set; }
        public double CPORCENTAJEDESCUENTO { get; set; }
        public int CIDVALORCLASIFCLIENTE1 { get; set; }
        public int CIDVALORCLASIFCLIENTE2 { get; set; }
        public int CIDVALORCLASIFCLIENTE3 { get; set; }
        public int CIDVALORCLASIFCLIENTE4 { get; set; }
        public int CIDVALORCLASIFCLIENTE5 { get; set; }
        public int CIDVALORCLASIFCLIENTE6 { get; set; }
        public int CIDVALORCLASIFPRODUCTO1 { get; set; }
        public int CIDVALORCLASIFPRODUCTO2 { get; set; }
        public int CIDVALORCLASIFPRODUCTO3 { get; set; }
        public int CIDVALORCLASIFPRODUCTO4 { get; set; }
        public int CIDVALORCLASIFPRODUCTO5 { get; set; }
        public int CIDVALORCLASIFPRODUCTO6 { get; set; }
        public string CTIMESTAMP { get; set; }
        public int CTIPOPROMO { get; set; }
        public int CIDCPTODOC { get; set; }
        public int CSUBTIPO { get; set; }
        public string CHORAINI { get; set; }
        public string CHORAFIN { get; set; }
        public int CTIPOPRO { get; set; }
        public int CVALA { get; set; }
        public int CVALB { get; set; }
        public int CDIAS { get; set; }
        public System.DateTime CFECHAALTA { get; set; }
        public int CSTATUS { get; set; }
    }
}
