//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admTiposCambio
    {
        public int CIDTIPOCAMBIO { get; set; }
        public int CIDMONEDA { get; set; }
        public System.DateTime CFECHA { get; set; }
        public double CIMPORTE { get; set; }
        public string CTIMESTAMP { get; set; }
    }
}
