//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admUnidadesMedidaPeso
    {
        public int CIDUNIDAD { get; set; }
        public string CNOMBREUNIDAD { get; set; }
        public string CABREVIATURA { get; set; }
        public string CDESPLIEGUE { get; set; }
        public string CCLAVEINT { get; set; }
        public string CCLAVESAT { get; set; }
    }
}
