//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admVistasCampos
    {
        public int CIDAUTOINCSQL { get; set; }
        public int CIDSISTEMA { get; set; }
        public int CIDIDIOMA { get; set; }
        public int CIDMODULO { get; set; }
        public string CNOMBRENATIVOTABLA { get; set; }
        public string CNOMBRENATIVOCAMPO { get; set; }
        public string CNOMBREAMIGABLECAMPO { get; set; }
        public int CANCHOCA01 { get; set; }
        public int CCAMPOOC01 { get; set; }
        public int CCAMPOOR01 { get; set; }
        public int CTIPOCAMPO { get; set; }
        public int CCALCULADO { get; set; }
        public int CDECIMALES { get; set; }
        public int CALINEAR { get; set; }
        public int CFORMATEAR { get; set; }
    }
}
