//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admVistasConsulta
    {
        public int CIDCONSULTA { get; set; }
        public int CIDSISTEMA { get; set; }
        public int CIDIDIOMA { get; set; }
        public int CIDMODULO { get; set; }
        public int CTIPO { get; set; }
        public int CCOLUMNASOCULTAR { get; set; }
        public string CNOMBRECONSULTA { get; set; }
        public string CSENTENCIASQL { get; set; }
        public int CIDEMPRESA { get; set; }
        public string CINDICE { get; set; }
        public int CESDESIS01 { get; set; }
        public string CFILTROS { get; set; }
        public int CINICIOARG { get; set; }
        public int CLIMITEARG { get; set; }
        public int CORDEN { get; set; }
    }
}
