//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admVistasRelacione
    {
        public int CIDRELACION { get; set; }
        public int CIDSISTEMA { get; set; }
        public int CIDIDIOMA { get; set; }
        public string CNOMBRENATIVOTABLA1 { get; set; }
        public string CNOMBRENATIVOTABLA2 { get; set; }
        public string CNOMBRERELACION { get; set; }
        public string CSENTENCIAENLACE { get; set; }
        public string CCAMPONA01 { get; set; }
        public string CFILTRO { get; set; }
        public string CTABLAREL1 { get; set; }
        public string CTABLAREL2 { get; set; }
        public string CFILTROAUX { get; set; }
    }
}
