//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admVistasRecurso
    {
        public int CIDAUTOINCSQL { get; set; }
        public int CIDSISTEMA { get; set; }
        public int CIDIDIOMA { get; set; }
        public int CIDMODULO { get; set; }
        public string CTABLABASE { get; set; }
        public string CTABLARELA { get; set; }
        public string CCAMPOBASE { get; set; }
        public string CCAMPOID { get; set; }
        public string CTITULO0 { get; set; }
        public string CCAMPO0 { get; set; }
        public string CINDICE0 { get; set; }
        public int CANCHO0 { get; set; }
        public string CTITULO1 { get; set; }
        public string CCAMPO1 { get; set; }
        public string CINDICE1 { get; set; }
        public int CANCHO1 { get; set; }
        public string CRANGO { get; set; }
    }
}
