//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class admVistasTabla
    {
        public int CIDAUTOINCSQL { get; set; }
        public int CIDSISTEMA { get; set; }
        public int CIDIDIOMA { get; set; }
        public int CIDMODULO { get; set; }
        public string CNOMBRENATIVOTABLA { get; set; }
        public string CNOMBREAMIGABLETABLA { get; set; }
        public int CORDEN { get; set; }
        public string CINDICES { get; set; }
    }
}
