//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class deudroe
    {
        public int ID { get; set; }
        public string Cliente { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Abonos { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    }
}
