//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> FechaN { get; set; }
        public Nullable<decimal> FolioN { get; set; }
        public string FechaTime { get; set; }
        public string ClientesN { get; set; }
        public Nullable<decimal> UnidadesN { get; set; }
        public string ProductoN { get; set; }
        public string Detalles1N { get; set; }
        public string Detalles2 { get; set; }
        public Nullable<decimal> TotalN { get; set; }
        public Nullable<decimal> Payment1 { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Observations { get; set; }
        public string Recibio { get; set; }
        public Nullable<decimal> FolioPago { get; set; }
        public Nullable<int> Authorize { get; set; }
    }
}
