//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class production
    {
        public int ID { get; set; }
        public bool ARM { get; set; }
        public bool ENTREG { get; set; }
        public string Armador { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public string ARM_Fecha { get; set; }
        public string ENTREG_Fecha { get; set; }
        public string ENTREG_User { get; set; }
    }
}
