//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPay
    {
        public Nullable<System.DateTime> FechaN { get; set; }
        public string ClientesN { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public int ID { get; set; }
    }
}
