//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class VREPGEN
    {
        public System.DateTime Fecha { get; set; }
        public double Folio { get; set; }
        public string Clientes { get; set; }
        public double Unidades { get; set; }
        public string Producto { get; set; }
        public string Detalles1 { get; set; }
        public string Detalles2 { get; set; }
        public double Total { get; set; }
        public int CIDMOVIMIENTO { get; set; }
    }
}
